version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: geo_referral_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Times
      POSTGRES_DB: georeferrals
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
